apiVersion: extensions/v1beta1 
kind: Deployment 
metadata: 
  name: inject 
spec: 
  replicas: 1 
  template: 
    metadata: 
      labels: 
        app: http-server-injec 
    spec: 
      containers: 
      - name: node-server 
        image: tz70s/node-server 
        ports: 
        - containerPort: 8181 
      - name: injector 
        image: tz70s/fault-injector 
        ports: 
        - containerPort: 8282 
        command: ["/app/injector","8181"]
